on:
  push:
    branches:
      - 'main'

name: Deploy on develop server
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies and build the project
        run: |
          npm install
          npm run build
      - name: Publish to hosting
        uses: sand4rt/ftp-deployer@v1.4
        with:
          sftp: true
          host: ${{ secrets.SFTP_HOSTNAME }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          local_folder: './build/'
          remote_folder: '/home/ipos/public_html/mblb/admin/dev'